### ISSUE TITLE
what kind of preprocessed data for the cloud? raw, weekly leads and/or anomalies?

### ISSUE THREAD

**Issue by aaronspring** [judithberner/climpred_CESM1_S2S#5]
when looking into /glade/campaign/cesm/development/cross-wg/S2S/jaye, I see many zarrs for raw model output, anomalies, climatologies, etc. @judithberner @abjaye

Should all those zarrs eventually end up in the cloud? First I only thought of the multi-simulation raw model output in zarr. If more, then we should use `intake-esm` without doubt, see https://github.com/intake/intake-esm/issues/325

I think this is a question of storage vs compute: All can be computed from raw model output.
- Anomaly zarr is as large as raw model output zarr I guess. So this would double the storage.
- weekly leads would add 1/7 of raw model output zarr
- climatology would add just a tiny fraction, 365days or 51 weeks x 360 lons x 180 lats

related to #3

**Comment by judithberner** [comment]
I agree, only the raw output should be converted. That is - for CESM -  everything under:
/glade/campaign/cesm/development/cross-wg/S2S/CESM2/S2SHINDCASTS

The files under /glade/campaign/cesm/development/cross-wg/S2S/jaye 
might be useful to pre-compute for the summer colloquium, but not uploaded in the cloud (unless maybe temporarily).
