### ISSUE TITLE
Issues/Requests/Bugs for climpred important for ASP21

### ISSUE THREAD

**Issue by aaronspring** [judithberner/climpred_CESM1_S2S#6]
Please raise issues in https://github.com/pangeo-data/climpred/issues

Also if you think the documentation is missing critical climpred information.

Project board summarizing (collection of issues I want to close within the next two months):
https://github.com/pangeo-data/climpred/projects/6#card-55839209

ASP label originally intending from Riley and me to attract new python-savvy collaborators:
https://github.com/pangeo-data/climpred/issues?q=is%3Aissue+is%3Aopen+label%3A%22ASP+Projects%22
These idea for pull requests, new metrics, new features for climpred ...

**Comment by judithberner** [comment]
https://github.com/judithberner/climpred_CESM1_S2S/issues/7
https://github.com/judithberner/climpred_CESM1_S2S/issues/8
Update Docu (we can help).

**Comment by judithberner** [comment]
@aneeshsc
