### ISSUE TITLE
Add climatology as 'reference'

### ISSUE THREAD

**Issue by judithberner** [judithberner/climpred_CESM1_S2S#8]
@aaronspring
You were waiting for this, correct? The docu says, open an issue :-)
We really want to have the RPSS wrt climatology. The good thing is that - thanks to  @bradyrx !!!!- we 
compute the climatology in 
https://github.com/judithberner/climpred_CESM1_S2S/blob/main/0.02_generate_climatology_S2S.ipynb

Can this be added as reference, please?

Related to  issue 
https://github.com/judithberner/climpred_CESM1_S2S/issues/7
it should be considered if the reference should be computed outside and passed into 
hindcast2_djf.verify(metric="rps",...)

**Comment by judithberner** [comment]
@abjaye

**Comment by aaronspring** [comment]
Thanks @judithberner. Could you please open this issue in climpred and explain how a persistence or climatological forecast for probabilistic metrics looks like? For deterministic we just prescribe a constant or seasonally vary forecast but I don’t know what the assumption would be for probabilistic? What’s the member dim? Or is just clim probability needed?

**Comment by aaronspring** [comment]
Related issue about more reference forecasts: https://github.com/pangeo-data/climpred/issues/202

**Comment by aaronspring** [comment]
I went back into my SubX freeze example. There I used the observations.mean(‘time’) (maybe better time.day of year or time.weekofyear) as the climatology no resolution line in the reliability plot
